<?php
/**
 * @file
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\packplm\Controller\PackController;

/**
 * @author 2C Solution
 * Implementation for hook_theme()
*/

function packplm_theme($existing, $type, $theme, $path) {
  return array(
    'packs' => array(
      'variables' => 
        array(
        'packs' => NULL
        )
    ),
    'mail' => array(
      'variables' => 
        array(
          'mail' => NULL
        )
    ),
  );
}

/**
 * Implements hook_mail().
*/
function packplm_mail($key, &$message, $params)
{
  switch ($key) {
    // mail etudiant
    case 'packplm_new_pack':
    case 'packplm_two_pack':
    case 'packplm_status_two_pack':
    case 'packplm_status_new_pack':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
    break;
  }  
}


